### ISSUE TITLE
Changing sound mode and sound source

### ISSUE THREAD

**Issue by debu-rnpr** [beeping-io/sdk-android#2]
Hi,

**Firstly lots of thanks for such a great project and making it open source**  
I have 2 questions -

1. Is there any method exposed from JNI side to set sound mode(BEEPING_MODE_NONAUDIBLE, BEEPING_MODE_AUDIBLE) ?  as there are few scenarios where we don't want the user to hear any sound

2. Is there any method exposed from JNI side to play sound from a byte array(or string), so that mobile device can create and play the sound itself

**Comment by alfredrc** [comment]
Hello Debabrata,

To ask these questions, the answer is YES for both questions. But we need to activate this access to the JNI. 

Could you create two issues separately ?

So, I will open the JNI access this week!!

**Comment by debu-rnpr** [comment]
sure
